name: station_stamp2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  bubble: ^1.2.1
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_map: ^5.0.0
  flutter_native_splash: ^2.3.1
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.3.7
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/train.jpeg"
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
